Repository barcradio/ultra-tracker, pull requests merged in 2024-09, with the labels that each got.

#91 Added support in backend for DNF type
  resources/config/bear-100-dnf-template.csv
  src/main/database/athlete-db.ts
  src/main/database/table-definitions.ts
  src/shared/enums.ts
  src/shared/models.ts
Labels: back-end

#92 Implemented Station identity
  src/main/database/stations-db.ts
  src/main/ipc/footer-ipc.ts
  src/main/ipc/init-ipc.ts
  src/renderer/src/features/Footer/Footer.tsx
  src/renderer/src/hooks/data/useStationIdentity.tsx
  src/shared/models.ts
Labels: feature, front-end, back-end

#93 refactor: timing records are marked sent, and unsent if export fails
  src/main/database/runners-db.ts
  src/main/database/timingRecords-db.ts
Labels: bug, back-end

#94 docs(help): updated help with additional formatter, added About section
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/renderer/src/assets/documents/get-started.md
  src/renderer/src/components/RenderMarkdown.tsx
Labels: documentation

#96 Set DNF
  src/main/database/athlete-db.ts
  src/main/ipc/athletes-ipc.ts
  src/main/ipc/dbsettings-ipc.ts
  src/renderer/src/features/RunnerEntry/EditRunner.tsx
  src/renderer/src/features/RunnerEntry/RunnerEntry.tsx
  src/renderer/src/features/RunnerEntry/RunnerFormStats.tsx
  src/renderer/src/hooks/data/useAthlete.tsx
  src/renderer/src/hooks/data/useRunnerData.tsx
  src/renderer/src/hooks/data/useTiming.tsx
  src/shared/models.ts
Labels: feature, front-end, back-end

#97 Help doc images
  electron.vite.config.cjs
  src/renderer/public/img/keyboard-layout.png
  src/renderer/src/assets/documents/get-started.md
Labels: documentation

#101 Fix table validation, dupe handling, Stations page, etc
  src/main/database/athlete-db.ts
  src/main/database/runners-db.ts
  src/main/database/table-definitions.ts
  src/main/database/tables-db.ts
  src/main/database/timingRecords-db.ts
  src/main/ipc/settings-ipc.ts
  src/main/lib/rfid-util.ts
  src/renderer/src/features/DBsettingsHub/DBsettingsHub.tsx
  src/renderer/src/features/RunnerEntry/EditRunner.tsx
  src/renderer/src/features/RunnerEntry/RunnerEntry.tsx
  src/renderer/src/features/SettingsHub/SettingsHub.tsx
  src/renderer/src/features/Sidebar/Sidebar.tsx
  src/renderer/src/features/StationsPage/StationsPage.tsx
  src/renderer/src/hooks/ipc/useSettingsUtilities.tsx
  src/renderer/src/routeTree.gen.ts
  src/renderer/src/routes/database.lazy.tsx
  src/renderer/src/routes/stations.lazy.tsx
Labels: front-end, back-end

#104 Fixed app not launching on new install
  package.json
  pnpm-lock.yaml
  resources/config/default-settings.json
  resources/config/stations-template.json
  src/main/index.ts
  src/main/lib/file-dialogs.ts
  src/preload/data.ts
Labels: back-end

#107 Refactor import export with dnf fields
  resources/config/bear100-2024-stations.json
  src/main/database/athlete-db.ts
  src/main/database/runners-db.ts
  src/main/ipc/athletes-ipc.ts
  src/main/lib/file-dialogs.ts
  src/renderer/src/features/SettingsHub/SettingsHub.tsx
  src/shared/models.ts
Labels: back-end

#108 Update help doc with graphics and other fixes
  .vscode/settings.json
  src/renderer/public/img/Athlete-edit.png
  src/renderer/public/img/Bib.png
  src/renderer/public/img/Logs-page.png
  src/renderer/public/img/Stations.png
  src/renderer/public/img/Stats.png
  src/renderer/public/img/export-page.png
  src/renderer/public/img/help-page.png
  src/renderer/public/img/roster-page.png
  src/renderer/public/img/settings-page.png
  src/renderer/public/img/stats-page.png
  src/renderer/public/img/theme-page.png
  src/renderer/src/assets/documents/get-started.md
Labels: documentation

#109 Improve comprehension of causes of warnings/errors
  src/main/database/runners-db.ts
  src/main/lib/stat-engine.ts
  src/renderer/src/features/RunnerEntry/Stats.tsx
  src/renderer/src/hooks/data/useStatsData.tsx
Labels: enhancement, front-end, back-end

#110 Initial stations data grid
  src/renderer/src/features/StationsPage/StationsPage.tsx
Labels: feature, front-end

#112 fix(workflow): github actions need permissions to update releases
  .github/workflows/release.yml
Labels: dev-ops

#113 fix: fixed an issue where a zero value station ID was interpreted as …
  src/main/database/athlete-db.ts
Labels: bug

#115 Fix appsettings stats
  .vscode/settings.json
  package.json
  src/main/database/athlete-db.ts
  src/main/database/runners-db.ts
  src/main/database/stations-db.ts
  src/preload/data.ts
Labels: bug, back-end

#116 Fixes for loading stations in release install
  .vscode/settings.json
  package.json
  src/main/database/athlete-db.ts
  src/main/database/runners-db.ts
  src/main/database/stations-db.ts
  src/preload/data.ts
Labels: bug, back-end

#117 refactor: removed electron-settings in favor of electron-store
  package.json
  pnpm-lock.yaml
  src/main/database/athlete-db.ts
  src/main/database/eventLogger-db.ts
  src/main/database/runners-db.ts
  src/main/database/stations-db.ts
  src/main/database/timingRecords-db.ts
  src/main/index.ts
  src/main/ipc/settings-ipc.ts
  src/main/lib/file-dialogs.ts
  src/main/lib/logger.ts
  src/main/lib/store.ts
  src/preload/data.ts
  src/renderer/src/features/StationsPage/StationsPage.tsx
  src/renderer/src/hooks/data/useStation.tsx
Labels: back-end

#118 Replaced electron-settings with electron-store and fixed pkg dependencies
  package.json
  pnpm-lock.yaml
  src/main/database/athlete-db.ts
  src/main/database/eventLogger-db.ts
  src/main/database/runners-db.ts
  src/main/database/stations-db.ts
  src/main/database/timingRecords-db.ts
  src/main/index.ts
  src/main/ipc/settings-ipc.ts
  src/main/lib/file-dialogs.ts
  src/main/lib/logger.ts
  src/main/lib/store.ts
  src/preload/data.ts
  src/renderer/src/features/StationsPage/StationsPage.tsx
  src/renderer/src/hooks/data/useStation.tsx
Labels: feature, back-end

#146 docs(help): minor edits and fixing images
  src/renderer/public/img/athlete-edit.png
  src/renderer/public/img/bib.png
  src/renderer/public/img/logs-page.png
  src/renderer/public/img/stations.png
  src/renderer/public/img/stats.png
  src/renderer/src/assets/documents/get-started.md
Labels: documentation

#150 128 Added In / Out roster status
  package.json
  pnpm-lock.yaml
  src/main/database/athlete-db.ts
  src/main/database/connect-db.ts
  src/main/database/migrations-db.ts
  src/main/database/runners-db.ts
  src/main/database/tables-db.ts
  src/main/database/timingRecords-db.ts
  src/main/lib/logger.ts
  src/renderer/src/components/Tag.tsx
  src/renderer/src/features/RosterPage/RosterPage.tsx
  src/renderer/src/features/StationsPage/StationsPage.tsx
  src/shared/enums.ts
  src/shared/models.ts
Labels: feature

#154 fixed duplicate handling for entry on Stats page
  src/main/database/runners-db.ts
  src/main/database/timingRecords-db.ts
Labels: back-end

#156 Revert change to prevent empty strings from being set to note fields
  src/main/database/athlete-db.ts
Labels: bug

#157 fix: updated tags to better colors and fixed syntax
  src/renderer/src/components/Tag.tsx
  src/renderer/src/features/RosterPage/RosterPage.tsx
Labels: bug, front-end

#161 Fix toasts and note handling for duplicates
  src/main/database/timingRecords-db.ts
  src/renderer/src/hooks/data/useTiming.tsx
Labels: back-end

#162 feat: add database backup on a 5 minute interval
  src/main/database/connect-db.ts
  src/renderer/src/assets/documents/get-started.md
Labels: back-end

#168 Added fast mode handling in timing records
  src/main/database/timingRecords-db.ts
Labels: back-end

#169 add a label to the Stations Page to indicate the entrymode
  src/renderer/src/features/StationsPage/StationsPage.tsx
Labels: feature, front-end

#171 Fix various bugs with notes, statuses, and dupes
  src/main/database/athlete-db.ts
  src/main/database/timingRecords-db.ts
Labels: bug, back-end

#174 fixed csv parser throwing runtime exceptions and fixed toasts
  src/main/database/athlete-db.ts
  src/main/database/runners-db.ts
Labels: bug, back-end

#180 Fixes for release version, bump to v1.0.2
  package.json
  src/main/database/connect-db.ts
  src/main/database/runners-db.ts
  src/main/database/tables-db.ts
  src/main/database/timingRecords-db.ts
  src/main/index.ts
  src/main/lib/file-dialogs.ts
  src/main/lib/logger.ts
  src/renderer/src/components/Tag.tsx
  src/renderer/src/hooks/data/useTiming.tsx
Labels: bug

#182 fix: need to also invalidate the stats table when updated dns/dnf
  src/renderer/src/hooks/data/useAthlete.tsx
Labels: bug

#183 need to also invalidate the stats table when updated dns/dnf
  src/renderer/src/hooks/data/useAthlete.tsx
Labels: bug
